#!/usr/bin/env bash

POTATO=2

function __load() {
	POTATO_APP_ROOT=$(pwd)
	[ -z "$POTATO_ROOT" ] && POTATO_ROOT=$(dirname $(whereis_realpath "$1"))

	POTATO_DEFAULT_ID="default"
	POTATO_DEFAULT_TASK="__main"

	potato_set_env POTATO_ENV_DEBUG ""
}

function potato_set_env() {
	local var_name=$1
	local default
	[ -z "$2" ] && default="" || default="$2"
	[ -z "${!var_name}" ] && printf -v "$var_name" '%s' "$default"
}

function potato_debug() {
	local __line_number=$BASH_LINENO
 	local __func_name=${FUNCNAME[1]}
 	local __source=$(basename ${BASH_SOURCE[1]})
	local prefix="[DEBUG $__func_name() in $__source:$__line_number] "
	local message
	[ -z "$1" ] && message="$prefix" || message="$prefix$1"
	[ $POTATO_ENV_DEBUG ] && echo $message
}

function potato_process_input_args() {
	POTATO_THIS_ID=$POTATO_DEFAULT_ID
	[ ! -z "$1" ] && POTATO_THIS_TASK="$1" || POTATO_THIS_TASK="$POTATO_DEFAULT_TASK"
	if [ ! -z "$(potato_task_exists $POTATO_THIS_TASK)" ]; then
		POTATO_THIS_ARGS=("${@:2}")
	elif [ "$#" -gt "1" ] && [ ! -z "$(potato_task_exists $2)" ]; then
		POTATO_THIS_ID=$1
		POTATO_THIS_TASK=$2
		POTATO_THIS_ARGS=("${@:3}")
	else
		POTATO_THIS_TASK="$POTATO_DEFAULT_TASK"
		POTATO_THIS_ARGS=("${@:1}")
	fi
}

function potato_task_exists() {
	local task=$1
	[ -e "$(potato_task_path $task)" ] && echo "1" || echo ""
}

function potato_task_path() {
	local task=$1
	echo "$POTATO_APP_ROOT/tasks/$task"
}

function potato_get_id() {
	echo $POTATO_THIS_ID
}

function potato_get_task() {
	echo $POTATO_THIS_TASK
}

function potato_get_arg() {
	local index=$1
	echo ${POTATO_THIS_ARGS[$index -1]}
}

function potato_get_args() {
	echo ${POTATO_THIS_ARGS}
}

function potato_test_args() {
	echo "ID: 	"$(potato_get_id)
	echo "TASK:	"$(potato_get_task)
	echo "ARG[1]:	"$(potato_get_arg 1)
	echo "ARG[2]:	"$(potato_get_arg 2)
	args=$(potato_get_args)
	echo "ARG[1]:	"${args[0]}
	echo "ARG[2]:	"${args[1]}
}

function potato_load_task() {
	local path=$(potato_task_path $1)
	[ -e $path ] && . $path || potato_debug "Failed to load $path"
}

function potato_exec() {
	potato_process_input_args "${@}"
	potato_load_task $(potato_get_task)
	run
}

function run() {
	potato_debug 'ERROR You need to implement run() in tasks/'$(potato_get_task)
}

function potato_input() {
	local message;
	[ -z "$1" ] && message="" || message="$1"
	local default;
  [ -z "$2" ] && default="" || default="$2"
	read -p "$message" value
	[ -z "$value" ] && value=$default
	echo $value
}

__load "${@}"
