#!/usr/bin/env bash

function deploy_main() {
  deploy_append bashrc.append $HOME/.bashrc POTATO_PATH_PLACEHOLDER $(pwd)
}

function deploy_append() {
  src=$1
  dest=$2
  text1=$3
  text2=$4
  
  text1=$(echo "$text1" | sed 's/\//\\\//g')
  text2=$(echo "$text2" | sed 's/\//\\\//g')

  echo "Appending $src to $dest"
  sed -e "s/$text1/$text2/" $src >> $dest

}

deploy_main

