#!/usr/bin/env bash

function run() {
  _script_commands=$(ls $POTATO_ROOT/tasks)
  complete -o nospace -F _script potato
}

# Copyright https://askubuntu.com/a/483149
_script()
{
  _script_commands=$(ls $POTATO_ROOT/tasks)
  local cur
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "${_script_commands}" -- ${cur}) )

  return 0
}
