#!/usr/bin/env bash

function run() {
  local addin_name=$(potato_get_arg 1)
  local paths=()
  paths[0]=$HOME/.potato
  paths[1]=$POTATO_ROOT
  for p in "${paths[@]}"; do
    local src=$p/available/$addin_name.bashrc
    [ -f $src ] && ln --symbolic --force $src $HOME/.potato/enabled/
  done
}
function __autocomplete() {
  local paths=()
  paths[0]=$HOME/.potato
  paths[1]=$POTATO_ROOT
  for p in "${paths[@]}"; do
    ls $p/available | sed 's/.bashrc//'
  done
}
function __help() {
  echo "
Enables an addin to be loaded in .bashrc

Usage: potato enable [addin_name]
  "
}
