#!/usr/bin/env bash

function run() {
  local addin_name=$1
  IFS=':' read -ra CONFIG_DIRS <<< "$POTATO_CONFIG_DIRS"
  for p in "${CONFIG_DIRS[@]}"; do
    echo looking at $p
    local src=$p/available/$addin_name
    [ -f $src ] && ln --symbolic --force $src $HOME/.potato/enabled/
  done
}
function __autocomplete() {
  local paths=()
  eval $(potato_declare_paths)
  for p in "$XDG_CONFIG_DIRS"; do
    ls $p/available
  done
}
function __help() {
  echo '
Usage: potato enable [addin_name]

Enables an addin from a list of available add-ins.
There are three forms of add-ins:
*.bashrc # loads as part of .bashrc or .bash_profile
*.precommand # executes before every command
*.postcommand # executes after every command
  '
}
