#!/usr/bin/env bash

function run() {
  local task=$1
  [ -z "$task" ] && task=$POTATO_THIS_TASK
  potato_load_task $task
  __help
}
function __help() {
  echo ''
  echo 'Available tasks:'
  #$(ls $POTATO_ROOT/tasks | xargs printf '- %s\n')
  printf ' - %s\n' $(potato_tasks_list)
  echo ''
  echo 'Available functions:'
  printf ' - %s\n' $(declare -F | cut -d' ' -f3 | grep potato | grep '^potato_.*')
  echo ''
  echo 'Available environmental variables:'
  printf ' - %s\n' $(printenv | grep '^POTATO')
  # @TODO below is failed attempt to properly display all variables using declare.
  #IFS="\n"; printf ' - %s\n' "$(declare -p | grep '\sPOTATO')"
}
function __autocomplete() {
  ls $POTATO_ROOT/tasks
}
