#!/usr/bin/env bash

function run() {
  local task=$(potato_get_arg 1)
  [ -z "$task" ] && task=$(potato_get_task)
  potato_load_task $task
  __help
}
function __help() {
  echo ''
  echo 'Available tasks:'
  #$(ls $POTATO_ROOT/tasks | xargs printf '- %s\n')
  printf ' - %s\n' $(potato_tasks_list)
  echo ''
  echo 'Available functions:'
  printf ' - %s\n' $(declare -F | cut -d' ' -f3 | grep potato | grep '^potato_.*')
}
function __autocomplete() {
  ls $POTATO_ROOT/tasks
}
