#!/usr/bin/env bash

function run() {
  local append_text=$(sed "s#__PATH__#$POTATO_ROOT#g" <<< $(cat $POTATO_ROOT/bashrc.append))
  local bashrc_path=$(install_get_bashrc)
  echo "$append_text" >> $bashrc_path

  mkdir -p $HOME/.potato/available
  mkdir -p $HOME/.potato/enabled
}

function install_get_bashrc {
  install_prepare_bashrc
  echo $HOME/.bashrc
}

function install_prepare_bashrc {
  case $OSTYPE in darwin*)
    # we are inside a Mac!
    touch $HOME/.bash_profile
    ln -s $HOME/.bash_profile $HOME/.bashrc
  esac
  return
}
