#!/usr/bin/env bash

function run() {
  install_append bashrc.append $HOME/.bashrc $INSTALL_BEGIN $INSTALL_END
  install_template $HOME/.bashrc POTATO_PATH_PLACEHOLDER $POTATO_APP_ROOT/potato
  install_mkdir $HOME/.potato lib enabled
  ln --symbolic --force $POTATO_APP_ROOT/available $HOME/.potato/
}

function install_mkdir() {
  local __base=$1
  for var in "${@:2}"; do
    echo "Attempting creating directory $__base/$var"
    mkdir -p "$__base/$var"
  done
}

function install_append() {
  local src=$1
  local dest=$2
  echo "Appending $src to $dest"
  cat $src >> $dest
}

function install_template() {
  local file=$1
  local text1=$2
  local text2=$3
  text1=$(echo "$text1" | sed 's/\//\\\//g')
  text2=$(echo "$text2" | sed 's/\//\\\//g')
  sed -ie "s/$text1/$text2/" $file
}
