#!/usr/bin/env bash

function run() {
  IFS=':' read -ra paths <<< "$POTATO_CONFIG_DIRS"
  for p in "${paths[@]}"; do
    echo "Add-ins found in ${p}:"
    [ -d $p/available ] && printf ' - %s\n' $(ls $p/available/ 2>/dev/null) || echo ' * No add-in found'
  done
}
function __help() {
  echo '
Usage: potato list

Lists available add-ins from different paths.
There are three forms of add-ins:
*.bashrc # loads as part of .bashrc or .bash_profile
*.precommand # executes before every command
*.postcommand # executes after every command
  '
}
