#!/usr/bin/env bash

function run() {
  echo "It's a potato farm!"
  for f in $(find $HOME/.potato/enabled -name '*.bashrc'); do
    local addin_name=$([[ $f =~ ^.*\/(.*)\.bashrc ]] && echo ${BASH_REMATCH[1]})
    printf "Activating add-in '%s'\n" $addin_name
    . $f
  done
}
